id: I92D299E9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-13T19:17:35+00:00'
last_modified: '2022-06-10T04:39:01.334010+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27883
  title: རྒྱུད་སྡེ་ཀུན་བཏུས། （གློག་ཀླད་པར་མ།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    B664:
      image_group_id: I4649
      title: ''
      total_pages: 850
      order: 1
      base_file: B664.txt
    28C7:
      image_group_id: I4650
      title: ''
      total_pages: 698
      order: 2
      base_file: 28C7.txt
    9A03:
      image_group_id: I4651
      title: ''
      total_pages: 736
      order: 3
      base_file: 9A03.txt
    FFB3:
      image_group_id: I4652
      title: ''
      total_pages: 602
      order: 4
      base_file: FFB3.txt
    E8F4:
      image_group_id: I4653
      title: ''
      total_pages: 826
      order: 5
      base_file: E8F4.txt
    50EA:
      image_group_id: I4654
      title: ''
      total_pages: 784
      order: 6
      base_file: 50EA.txt
    838E:
      image_group_id: I4655
      title: ''
      total_pages: 834
      order: 7
      base_file: 838E.txt
    '3862':
      image_group_id: I4656
      title: ''
      total_pages: 794
      order: 8
      base_file: 3862.txt
    5B53:
      image_group_id: I4657
      title: ''
      total_pages: 696
      order: 9
      base_file: 5B53.txt
    C839:
      image_group_id: I4658
      title: ''
      total_pages: 816
      order: 10
      base_file: C839.txt
    '3408':
      image_group_id: I4659
      title: ''
      total_pages: 718
      order: 11
      base_file: 3408.txt
    AF9F:
      image_group_id: I4660
      title: ''
      total_pages: 610
      order: 12
      base_file: AF9F.txt
    114F:
      image_group_id: I4661
      title: ''
      total_pages: 682
      order: 13
      base_file: 114F.txt
    '5156':
      image_group_id: I4662
      title: ''
      total_pages: 706
      order: 14
      base_file: 5156.txt
    '6276':
      image_group_id: I4663
      title: ''
      total_pages: 686
      order: 15
      base_file: 6276.txt
    C9BB:
      image_group_id: I4664
      title: ''
      total_pages: 752
      order: 16
      base_file: C9BB.txt
    9FB6:
      image_group_id: I4665
      title: ''
      total_pages: 812
      order: 17
      base_file: 9FB6.txt
    D814:
      image_group_id: I4666
      title: ''
      total_pages: 702
      order: 18
      base_file: D814.txt
    BA5B:
      image_group_id: I4667
      title: ''
      total_pages: 690
      order: 19
      base_file: BA5B.txt
    9D0C:
      image_group_id: I4668
      title: ''
      total_pages: 784
      order: 20
      base_file: 9D0C.txt
    B7F1:
      image_group_id: I4669
      title: ''
      total_pages: 834
      order: 21
      base_file: B7F1.txt
    '2439':
      image_group_id: I4670
      title: ''
      total_pages: 776
      order: 22
      base_file: 2439.txt
    2D49:
      image_group_id: I4671
      title: ''
      total_pages: 916
      order: 23
      base_file: 2D49.txt
    6EB7:
      image_group_id: I4672
      title: ''
      total_pages: 654
      order: 24
      base_file: 6EB7.txt
    A6A9:
      image_group_id: I4673
      title: ''
      total_pages: 664
      order: 25
      base_file: A6A9.txt
    88F3:
      image_group_id: I4674
      title: ''
      total_pages: 670
      order: 26
      base_file: 88F3.txt
    '7838':
      image_group_id: I4675
      title: ''
      total_pages: 700
      order: 27
      base_file: 7838.txt
    AAC2:
      image_group_id: I4676
      title: ''
      total_pages: 672
      order: 28
      base_file: AAC2.txt
    F72B:
      image_group_id: I4677
      title: ''
      total_pages: 730
      order: 29
      base_file: F72B.txt
    BD82:
      image_group_id: I4678
      title: ''
      total_pages: 688
      order: 30
      base_file: BD82.txt
    7BF9:
      image_group_id: I4679
      title: ''
      total_pages: 612
      order: 31
      base_file: 7BF9.txt
    0D61:
      image_group_id: I4680
      title: ''
      total_pages: 918
      order: 32
      base_file: 0D61.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
